name: Django Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      PIPENV_VENV_IN_PROJECT: true
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      ENVIRONMENT: Test
      DATABASE_URL: postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@127.0.0.1:5432/django_test
      
    services:
      postgres:
        image: postgres:10-postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: django_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --fix-missing -y libev-dev direnv
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d --keep-outdated
        
    - name: Set up project
      run: |
        mkdir -p dist
        pipenv run django-admin startproject \
          --template=. \
          --name=env.example \
          --extension=py,md \
          django_project_template dist
        cd dist
        mv env.example env
        pipenv install -d --keep-outdated
        
    - name: Run tests
      run: |
        cd dist
        pipenv run python manage.py test --configuration=Test -v 2
